spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/img_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: true
